apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  namespace: kasten-io
  labels:
    app: basic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      strategy:
        type: Recreate
      containers:
      - name: basic-app-container
        image: alpine:3.7
        resources:
            requests:
              memory: 256Mi
              cpu: 100m
        command: ["tail"]
        args: ["-f", "/dev/null"]
        volumeMounts:
        - mountPath: /mnt/k10state
          name: jobs-persistent-storage
      volumes:
      - name: jobs-persistent-storage
        persistentVolumeClaim:
          claimName: jobs-pv-claim
